### ISSUE TITLE
Pokemon Sword

### ISSUE THREAD

**Issue by maikelcain** [Ryujinx/Ryujinx-Games-List#210]
Game name: Pokemon Sword

It does not show the texts. Ryujinx version 1.0.3237.

![Sin título](https://user-images.githubusercontent.com/28859778/69351117-0efa0b00-0c7b-11ea-90cd-5345ac3ae20e.png)
![Sin título2](https://user-images.githubusercontent.com/28859778/69351135-15888280-0c7b-11ea-8049-21d36ede54b3.png)
![Sin título3](https://user-images.githubusercontent.com/28859778/69351136-16b9af80-0c7b-11ea-88c7-ac9d68258834.png)

**Comment by AcK77** [comment]
Please, next time follow the issue template because you don’t follow it.
And issues are used for master build feedback. Who isn’t able to rendering something with this game. Because you use the ANGEL branch, at least you should specified it in the issue.
(I will close the issue if anything will be change!)
Thanks.

**Comment by maikelcain** [comment]
Sorry, I did not know. Where can I report errors or make inquiries?

**Comment by AcK77** [comment]
Then I close it.
Feel free to ask for help or report errors on our Discord server.
I don’t know what you want to mean by "inquiries"...
